service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: PJ@AWS
  region: ap-southeast-2

functions:
  productAPI:
    handler: Controller/product.handler
    events:
        - http:
            path: /index
            method: get
        - http:
            path: /
            method: post
        - http:
            path: /
            method: get
        - http:
            path: /{productId}
            method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin