service: serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: PJ@AWS
  region: ap-southeast-2

functions:
  productAPI:
    handler: Controller/product.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          
plugins:
  - serverless-offline
  - serverless-dotenv-plugin